const tocData = 
[
	["身の回り品","","PERSONAL ITEMS",1,[
		["男性用衣服","","",,[
			["ジャケットとベスト","","jacket and vest",2,[]],
			["シャツ","","shirt",3,[]],
			["ベルトとサスペンダー","","belt and suspenders",4,[]],
			["ズボン","","pants",5,[]],
			["ネックウェア","","neckwear",6,[]],
			["アンダーウェア","","underwear",8,[]]]],
		["女性用衣服","","",,[
			["アンダーウェア","","underwear",9,[]],
			["ジャケットとズボン","","jacket and pants",10,[]],
			["ブラウスとスカート","","blouse and skirt",11,[]],
			["ドレス","","dress",12,[]]]],
		["男女共通の衣服","","",,[
			["セーター","","sweater",13,[]],
			["外套","","outerwear",14,[]]]],
		["帽子","","",,[
			["紳士帽","","men's hats",16,[]],
			["婦人帽","","women's hats",17,[]]]],
		["履き物","","",,[
			["靴","","shoe",18,[]],
			["ブーツとサンダル","","boots and sandal",20,[]],
			["靴の付属品","","shoe accessories",21,[]]]],
		["留め具","","",,[
			["留め具","","fasteners",22,[]],
			["開閉具","","closures",23,[]]]],
		["ヘアースタイルと顔毛","","",,[
			["かみそり","","shavers",24,[]],
			["男性の髪","","men's hair",25,[]],
			["整髪用具","","hair grooming implements",26,[]],
			["女性の髪","","women's hair",27,[]],
			["ヘアスタイリングの用具","","hairstyling implements",28,[]]]],
		["化粧品","","",,[
			["歯ブラシ","","toothbrush",29,[]],
			["化粧、メーキャップ","","makeup",30,[]],
			["化粧品","","beauty products",31,[]]]],
		["宝石","","",,[
			["宝石","","gemstone",32,[]],
			["指輪","","ring",33,[]]]],
		["時計","","",,[
			["腕時計、懐中時計","","watches",34,[]]]],
		["めがね","","eyeglasses",35,[]],
		["かばん","","",,[
			["ハンドバッグ","","handbag",36,[]]]],
		["財布と通貨","","",,[
			["財布、札入れ","","wallet/billfold",37,[]]]],
		["通貨","","",,[
			["通貨","","money",38,[]],
			["硬貨","","coin",40,[]],
			["連邦準備制度","","Federal Reserve System/FRS",41,[]],
			["米国通貨","","U.S. currency",42,[]],
			["英国通貨","","British currency",44,[]]]],
		["小切手","","",,[
			["クレジットカード","","credit cards",46,[]],
			["小切手","","check",47,[]],
			["旅行小切手","","traveler's checks",48,[]],
			["為替","","money order",49,[]]]],
		["喫煙具","","",,[
			["葉巻と紙巻きたばこ","","cigar and cigarette",50,[]],
			["パイプ","","pipe",51,[]]]],
		["洋傘","","umbrella",52,[]]]],
	["ホーム","","HOME",53,[
		["住居","","",,[
			["住宅の外観","","house exterior",54,[]],
			["庭","","yard",55,[]],
			["住宅の外観","","house exterior",56,[]],
			["設計","","planning and design",57,[]],
			["ドア","","door",58,[]],
			["窓","","window",59,[]],
			["階段","","staircase",60,[]],
			["囲い、柵、垣、塀","","fence",61,[]],
			["基礎","","foundation",62,[]],
			["枠組","","frame",63,[]],
			["建材","","building materials",64,[]],
			["れんが壁","","brick wall",65,[]]]],
		["居間","","",,[
			["暖炉","","fireplace",66,[]],
			["時計","","clock",67,[]],
			["いす","","chair",68,[]],
			["安楽いす","","lounger",69,[]],
			["ソファ","","sofa",70,[]],
			["ろうそくと燭台","","candle and cendelabrum",71,[]],
			["電灯と照明","","lamps and lighting",72,[]],
			["照明器具","","lighting fixtures",74,[]],
			["窓おおい","","window coverings",75,[]]]],
		["寝室","","",,[
			["ベッドと寝具類","","bed and bedding",78,[]],
			["化粧台","","dressers",80,[]],
			["じゅうたん","","carpet",81,[]]]],
		["バスルーム","","",,[
			["蛇口と洗面台","","faucet and sink",82,[]],
			["バスルーム","","bathroom",83,[]],
			["浴室とシャワー","","bath and shower",84,[]],
			["便所","","toilet",85,[]]]],
		["食堂","","",,[
			["テーブル","","table",86,[]],
			["食器戸棚","","side pieces",87,[]],
			["プレースセッティング","","place setting",88,[]],
			["デザート用食器","","dessert setting",89,[]],
			["ワイン","","wine",90,[]],
			["茶","","tea",91,[]],
			["コーヒー沸かし器","","coffee makers",92,[]]]],
		["台所","","",,[
			["流しとごみ圧縮機","","sink and compactor",94,[]],
			["料理用レンジ","","stove/range",95,[]],
			["冷蔵庫","","refrigerator",96,[]],
			["皿洗い機","","dishwasher",97,[]],
			["缶切り","","openers",98,[]],
			["トースター","","toaster",99,[]],
			["調理器具","","food processor",100,[]],
			["ジュース絞り器","","juicers",101,[]],
			["包丁","","knife",102,[]],
			["なべ類","","pots and pans",103,[]],
			["混合器具と計量器具","","mixing and measuring tools",104,[]],
			["調理器具","","preparation utensils",105,[]],
			["こし器と水切り用具","","strainers and drainers",106,[]],
			["粉砕機、おろし器","","cutters, grinders and graters",107,[]],
			["原材料","","raw ingredients",108,[]],
			["加工食品","","prepared foods",109,[]],
			["デザート","","desserts",110,[]],
			["スナック","","snack food",111,[]],
			["入れ物","","containers",112,[]],
			["ラベルとパッケージ","","labeling and packaging",114,[]]]],
		["ユーティリティルーム","","",,[
			["机","","desk",116,[]],
			["机上備品","","desktop equipment",117,[]],
			["ミシン","","sewing machine",120,[]],
			["アイロン","","iron",121,[]],
			["洗濯と乾燥","","washing and drying",122,[]],
			["家庭用掃除用具","","household cleaning equipment",124,[]],
			["電気掃除機","","vacuum cleaner",125,[]]]],
		["安全用具","","",,[
			["消火用具","","firefighting devices",126,[]]]],
		["バッグ","","",,[
			["旅行かばん","","luggage",127,[]]]],
		["中庭","","",,[
			["子供用具","","children's gear",128,[]],
			["裏庭用設備","","backyard equipment",129,[]],
			["中庭用アクセサリー","","patio accessories",130,[]]]]]],
	["医療","","MEDICINE",,[
		["病気","","",,[
			["病気の名称","","disease",132,[]]]],
		["専門医","","specialists",133,[]],
		["病院","","",,[
			["病院と患者","","hospitals and patients",134,[]],
			["処方せん","","prescription",135,[]]]],
		["医療器具","","",,[
			["診療器具","","examination equipment",136,[]],
			["治療補助具","","treatment aids",137,[]],
			["処置台","","medical table",138,[]],
			["補助器具","","supportive devices",139,[]],
			["診療器具","","examination equipment",140,[]],
			["歯科矯正器具","","dental corrective devices",141,[]],
			["歯科機器","","dental unit",142,[]],
			["歯科用具","","dental equipment",143,[]]]],
		["歯","","teeth",144,[]]]],
	["交通","","TRANSPORTATION",145,[
		["自動車","","",,[
			["自動車／外観（オールドカー）","","automobile/car exterior(old car)",146,[]],
			["自動車／外観","","automobile/car exterior",148,[]],
			["自動車の内装","","automobile interior",149,[]],
			["乗用車のタイプ","","passenger car types",150,[]],
			["ボデーの形状","","body styles",151,[]],
			["乗用車のマーク","","trademarks of automobiles",152,[]],
			["車輪／タイヤ","","wheel/tire",153,[]],
			["自動車内部構造図","","automobile cutaway",154,[]],
			["自動車のエンジン","","automobile engine",156,[]],
			["ガソリンポンプ","","gasoline pump",158,[]],
			["交通管制装置","","traffic control devices",159,[]],
			["ハイウェイ","","highway",160,[]]]],
		["公共交通","","",,[
			["鉄道踏切","","railroad crossing",161,[]],
			["鉄道","","railroad",162,[]],
			["バス","","bus",166,[]],
			["地下鉄","","subway",168,[]],
			["タクシー","","taxi",169,[]]]],
		["運搬車","","",,[
			["トラック","","truck",170,[]]]],
		["緊急用車","","",,[
			["パトロールカー","","police car",172,[]],
			["救急車","","",173,[]],
			["消防自動車","","fire engine",175,[]]]],
		["公共サービス車","","",,[
			["レッカー車","","tow truck/wrecker",178,[]],
			["清掃作業車","","sanitation vehicles",179,[]]]],
		["サイクル","","",,[
			["自転車","","bicycle",180,[]],
			["オートバイ","","motorcycle",182,[]]]],
		["レクリエーション車","","recreation vehicles",184,[]],
		["馬車","","horse-drawn carriages",185,[]],
		["ボートと船舶","","",,[
			["船舶用語","","nautical terminology",186,[]],
			["漕艇","","rowboat/rowing boat",187,[]],
			["ヨット","","sailboat",188,[]],
			["帆","","sail",190,[]],
			["船外機","","outboard engine",191,[]],
			["モーターボート","","powerboat",192,[]],
			["タンカー","","tanker",194,[]],
			["客船／外洋航路船","","passenger ship/ocean liner",196,[]],
			["タグボート","","tugboat",198,[]],
			["消防艇","","fireboat",199,[]],
			["水中翼船","","hydrofoil",199,[]],
			["ホバークラフト","","hovercraft",200,[]]]],
		["航空機","","",,[
			["ヘリコプター","","helicopter",201,[]],
			["自家用機","","private aircraft",202,[]],
			["旅客機","","civil aircraft",204,[]],
			["ボーイング747の操縦席","","747 cockpit",208,[]]]],
		["宇宙船","","",,[
			["スペースシャトルと発射台","","space shuttle and launch pad",210,[]],
			["スペースシャトルフライトデッキ","","space shuttle flight deck",211,[]],
			["スペースシャトル","","space shuttle",212,[]],
			["月着陸船","","lunar lander",214,[]],
			["月面車","","lunar rover",215,[]],
			["スペースラブ、宇宙実験室","","space lab",216,[]],
			["宇宙服","","spacesuit",217,[]]]],
		["軽航空機","","lighter-than-air craft",218,[]]]],
	["情報伝達","","COMMUNICATIONS",219,[
		["印刷情報伝達","","",,[
			["ペンと鉛筆","","pen and pencil",220,[]],
			["通信文","","correspondence",221,[]],
			["封筒と切手","","envelope and stamps",222,[]],
			["履歴書","","resume",224,[]],
			["名刺","","cards",225,[]],
			["タイプライター","","typewriter",226,[]],
			["活版印刷","","typography",228,[]],
			["印刷工程","","printing processes",230,[]],
			["書籍","","book",232,[]],
			["雑誌の表紙と目次ページ","","magazine cover and contents page",234,[]],
			["雑誌記事","","magazine feature",236,[]],
			["新聞","","newspaper",239,[]]]],
		["コンピュータ","","",,[
			["コンピュータ","","computer",240,[]],
			["キーパンチ、鍵盤せん孔機","","key punch",242,[]],
			["光学式文字読み取り装置","","OCR",243,[]],
			["パーソナルコンピュータ、パソコン","","personal computer",244,[]]]],
		["ファクシミリ","","",,[
			["ファクシミリ／ファックス","","facsimile/fax",245,[]]]],
		["電話","","telephone",246,[]],
		["計算機","","",,[
			["金銭登録機","","cash register",248,[]],
			["計算器","","calculators",249,[]]]],
		["音声情報伝達","","",,[
			["テープレコーダー","","tape recorders",250,[]],
			["音響機器","","phonographic equipment",252,[]],
			["トランシーバー","","transceiver",255,[]]]],
		["視聴覚情報伝達","","",,[
			["テレビ","","television",256,[]],
			["テレビ番組表","","TV programs",257,[]],
			["ビデオレコーダー","","video recorder",258,[]],
			["ビデオディスク","","videodisc",259,[]]]],
		["視覚情報伝達","","",,[
			["カメラ","","still camera",260,[]],
			["フィルム","","film",263,[]],
			["写真用アクセサリー","","photographic accessories",264,[]],
			["ムービーカメラ","","movie camera",266,[]],
			["映写機","","projectors",268,[]]]],
		["情報伝達","","",,[
			["放送衛星","","broadcasting satellite",270,[]]]]]],
	["住居と建造物","","SHELTERS and STRUCTURES",271,[
		["特殊目的建築物","","",,[
			["米国国会議事堂","","Capitol",272,[]],
			["ホワイトハウス","","White House",274,[]],
			["法廷","","courtroom",276,[]],
			["刑務所","","prison",277,[]],
			["大学","","university",278,[]],
			["超高層ビル、摩天楼","","skyscraper",280,[]],
			["エレベーター","","elevator",282,[]],
			["エスカレーター","","escalator",284,[]],
			["空港","","airport",285,[]],
			["ターミナル","","terminal",288,[]],
			["操車場","","railroad yard",290,[]],
			["鉄道の駅","","railroad station",291,[]],
			["教会堂／大聖堂","","church/cathedral",292,[]],
			["教会の内部","","church interior",293,[]],
			["祭壇","","altar",294,[]],
			["シナゴーグ／ユダヤ教会堂","","synagogue/temple",295,[]],
			["サーカス","","circus",296,[]],
			["遊園地","","amusement park",299,[]]]],
		["その他の建造物","","",,[
			["橋","","bridge",303,[]],
			["可動橋","","movable bridge",304,[]],
			["橋","","bridges",305,[]],
			["トンネル","","tunnel",306,[]],
			["運河の閘門","","canal lock",307,[]],
			["ダム","","dam",308,[]],
			["海洋石油掘削装置","","oil drilling platform/offshore rig",309,[]]]],
		["建築デザイン","","",,[
			["世界の建築","","international architecture",310,[]],
			["アーチ","","arch",312,[]],
			["柱","","column",313,[]]]],
		["城と要塞","","",,[
			["城","","castle",314,[]],
			["要塞","","fortifications",316,[]]]],
		["ティピーとドーム","","",,[
			["ティピー","","tepee/teepee/tipi",318,[]],
			["ドーム型構造物","","domed structures",319,[]]]],
		["畜舎とサイロ","","barn and silo",320,[]]]],
	["スポーツとレクリエーション","","SPORTS and RECREATION",321,[
		["チームスポーツ","","",,[
			["野球","","baseball",322,[]],
			["フットボール","","football",328,[]],
			["ラグビー","","rugby football",332,[]],
			["アイスホッケー","","ice hockey",334,[]],
			["バスケットボール","","basketball",338,[]],
			["サッカー","","soccer",340,[]]]],
		["競争スポーツ","","",,[
			["陸上競技","","track and field",342,[]],
			["ランニングシューズ","","running shoe",344,[]],
			["フィールド競技器具（投てき）","","field events equipment",345,[]],
			["ハードル","","hurdle",346,[]],
			["棒高跳び","","pole vault",347,[]],
			["体操","","gymnastics",348,[]],
			["トランポリン","","trampoline",350,[]],
			["ボディービル","","body building",351,[]],
			["ボクシング","","boxing",352,[]],
			["ゴルフ","","golf",354,[]],
			["テニス","","tennis",358,[]],
			["ハンドボール","","handball",360,[]],
			["スカッシュ","","squash",361,[]],
			["ハイアライ／ペロタ","","jai alai/pelota",362,[]],
			["フェンシング","","fencing",363,[]],
			["水泳と飛び込み","","swimming and diving",364,[]],
			["バレーボール","","volleyball",366,[]],
			["バドミントンコート","","badminton court",367,[]],
			["シャッフルボードとクロッケー","","shuffleboard and croquet",368,[]],
			["ラクロス","","lacrosse",369,[]],
			["卓球","","ping-pong/table tennis",370,[]],
			["ボウリング","","bowling",371,[]]]],
		["個人スポーツ","","",,[
			["ローラースケートとスケートボーディング","","roller skating and skateboarding",372,[]],
			["アイススケート靴","","ice skates",373,[]],
			["アルペンスキー","","alpine skiing",374,[]],
			["ノルディックスキー","","Nordic skiing",376,[]],
			["そりとトボガン","","sledding and tobogganing",378,[]],
			["水上スキー","","waterskiing",379,[]],
			["サーフィン","","surfing",380,[]],
			["サーフ","","surf",381,[]],
			["ウィンドサーフィン","","windsurfing",382,[]],
			["スキンダイビング","","skin diving",384,[]],
			["熱気球","","hot air balloon",386,[]],
			["ハンググライディング","","hang gliding",387,[]],
			["パラシューティング／スカイダイビング","","parachuting/skydiving",388,[]],
			["登山","","mountain climbing",390,[]]]],
		["野外スポーツ","","",,[
			["キャンプ","","camping",392,[]],
			["バックパッキング","","backpacking",393,[]],
			["釣り","","fishing",396,[]]]],
		["馬術競技","","",,[
			["乗馬","","horse riding",398,[]],
			["馬具","","riding equipment",399,[]],
			["平地競走","","flat racing",400,[]],
			["出走表","","racing program entry",401,[]],
			["繋駕速走競争","","harness racing",402,[]]]],
		["自動車レース","","",,[
			["ドラッグレース","","drag racing",403,[]],
			["グランプリレース","","Grand Prix racing",405,[]]]],
		["ゲーム","","",,[
			["チェスとチェッカー","","chess and checkers",406,[]]]],
		["テーブルゲーム","","",,[
			["ビリヤードとプール","","billiards and pool",408,[]]]],
		["ボードゲーム","","",,[
			["バックギャモンと牌ゲーム","","backgammon and tile games",409,[]]]],
		["カジノゲーム","","",,[
			["トランプ","","playing cards",410,[]],
			["ギャンブル用具","","gambling equipment",412,[]]]],
		["ダーツ","","darts",415,[]],
		["たこ","","kites",416,[]]]],
	["芸術と工芸","","ARTS and CRAFTS",417,[
		["演劇","","",,[
			["舞台","","stage",418,[]],
			["劇場","","theater",419,[]]]],
		["音楽","","",,[
			["シートミュージックの楽譜","","sheet music notations",420,[]],
			["オーケストラ","","orchestra",422,[]],
			["バイオリン","","violin",424,[]],
			["木管楽器","","woodwinds",426,[]],
			["金管楽器","","brasses",428,[]],
			["オルガン","","organ",431,[]],
			["ピアノ","","piano",432,[]],
			["ギター","","guitar",434,[]],
			["エレクトリックギター","","electric guitar",436,[]],
			["ドラム","","drums",438,[]],
			["パーカッション","","percussion",439,[]],
			["民族楽器","","folk instruments",440,[]],
			["バグパイプ","","bagpipe",442,[]],
			["演奏用付属品","","musical accessories",443,[]]]],
		["美術","","",,[
			["コンポジションの原理","","elements of composition",444,[]],
			["彩色画","","painting",446,[]],
			["色","","colors",448,[]],
			["彫刻用具","","sculpting tools",449,[]],
			["陶器製作用具","","potting tools",451,[]],
			["木口木版印刷","","woodcut printing",452,[]],
			["シルクスクリーンとスクリムショウ","","silk screen and scrimshaw",453,[]],
			["リトグラフィー、石版印刷","","lithography",454,[]],
			["凹版印刷とエッチング","","intaglio and etching",455,[]],
			["ステンドグラス","","stained glass",456,[]],
			["額縁","","frame",457,[]]]],
		["漫画技法","","cartooning",458,[]],
		["工芸","","",,[
			["裁縫","","sewing",462,[]],
			["飾りステッチ","","decorative stitching",463,[]],
			["編物","","knitting",464,[]],
			["紡織","","weaving",465,[]],
			["型紙","","sewing pattern",466,[]]]]]],
	["サインとシンボル","","SIGNS and SYMBOLS",467,[
		["旗","","flags",468,[]],
		["紋章","","coat of arms",470,[]],
		["サインとシンボル","","",,[
			["道路標識","","road signs",472,[]],
			["案内標識、案内表示","","public signs",474,[]],
			["宗教上のシンボル","","religious symbols",476,[]],
			["（黄道）十二宮","","signs of the zodiac",477,[]],
			["科学・ビジネス・商業の記号","","symbols of science, business and commerce",478,[]],
			["トレードマーク","","trademark",480,[]],
			["ジェスチャー","","gestures",482,[]],
			["記号言語","","symbolic language",484,[]],
			["文法記号","","grammatical symbols",485,[]],
			["校正記号","","proofreader's marks",486,[]]]],
		["落書き","","",,[
			["ホーボーの記号","","hobo signs",487,[]]]],
		["墓石と棺","","tombstone and coffin",488,[]]]],
	["制服・衣装・礼装","","UNIFORMS, COSTUMES and CEREMONIAL ATTIRE",489,[
		["王室の正装","","",,[
			["王室の盛装","","royal regalia",490,[]],
			["王家の標章","","royal regalia",492,[]]]],
		["聖職者の衣装","","",,[
			["ユダヤ人の（宗教的）儀式用品目","","Jewish ritual items",494,[]],
			["聖職者用衣服","","religious vestments",495,[]]]],
		["民族衣装","","",,[
			["カウボーイ","","cowboy",496,[]],
			["インディアン","","Indian",497,[]],
			["民族服","","native dress",498,[]]]],
		["歴史的衣装","","historical costumes",499,[]],
		["演技者の衣装","","",,[
			["道化師","","clown",501,[]],
			["バレエダンサー","","ballet dancer",502,[]],
			["楽隊長、鼓手長","","drum major",503,[]]]],
		["結婚衣装","","",,[
			["花嫁と花婿","","bride and groom",504,[]]]],
		["召使いの衣装","","",,[
			["メイドと執事","","maid and butler",505,[]]]],
		["軍服","","military uniforms",506,[]],
		["地方自治体職員の制服","","",,[
			["警察官","","police officer",510,[]],
			["消防士","","fireman",512,[]]]]]],
	["兵器","","WEAPONS",513,[
		["死刑執行用装置","","execution devices",514,[]],
		["攻撃兵器","","",,[
			["刺・切の武器","","thrusting and cutting weapons",515,[]],
			["中世の武器","","medieval arms",516,[]],
			["弓と矢","","bow and arrow",517,[]]]],
		["防御兵器","","",,[
			["甲冑","","armor",518,[]],
			["大砲と投射機（カタパルト）","","cannon and catapult",520,[]]]],
		["小火器","","",,[
			["拳銃","","handguns",521,[]],
			["ピストル","","pistol",522,[]],
			["散弾銃とライフル銃","","shotgun and rifle",524,[]],
			["自動火器","","automatic weapons",526,[]],
			["迫撃砲とバズーカ砲","","mortar and bazooka",527,[]]]],
		["歩兵用兵器","","",,[
			["手榴弾（擲弾）と地雷","","grenade and mine",528,[]]]],
		["砲","","",,[
			["大砲","","gun",529,[]]]],
		["装甲戦闘車両","","",,[
			["戦車","","tank",530,[]]]],
		["戦闘艦","","",,[
			["水上戦闘艦","","surface fighting ship",532,[]],
			["航空母艦","","aircraft carrier",534,[]],
			["潜水艦","","submarine",536,[]]]],
		["戦闘用機","","",,[
			["戦闘機","","fighter",537,[]],
			["パイロットの航空計器盤","","pilot's instrument panel",538,[]]]],
		["ミサイル","","",,[
			["ミサイル","","missile",540,[]],
			["誘導方式","","guidance system",541,[]]]],
		["誘導兵器","","",,[
			["魚雷","","torpedo",542,[]]]]]],
	["機械と道具","","MACHINERY and TOOLS",543,[
		["エネルギーシステム","","",,[
			["風力システム","","wind systems",544,[]],
			["太陽熱システム","","solar power system",545,[]],
			["原子炉","","nuclear power reactor",546,[]],
			["送電線、真空管、トランジスタ","","power line, vacuum tube and transister",548,[]],
			["バッテリー","","battery",549,[]],
			["スイッチ、コンセント、プラグ","","switch, receptacle and plug",550,[]],
			["メーターとヒューズ箱","","meter and fuse box",551,[]]]],
		["薪ストーブ","","woodburning stove",552,[]],
		["エンジン","","",,[
			["蒸気機関","","steam engine",553,[]],
			["内燃機関","","internal combustion engine",554,[]]]],
		["動力システム","","",,[
			["ジェットエンジン","","jet engine",555,[]]]],
		["環境調節装置","","",,[
			["ファーネス","","furnace",556,[]],
			["給湯器",""," hot water heater",557,[]],
			["空調","","air conditioning",558,[]],
			["熱交換器","","heat exchanger",559,[]]]],
		["家庭用工具","","",,[
			["作業台","","workbench",560,[]],
			["締め具、クランプ","","clamps",561,[]],
			["くぎとねじ","","nails and screws",562,[]],
			["ナットとボルト","","nuts and bolts",563,[]],
			["ハンマー","","hammer",564,[]],
			["ドライバー","","screwdriver",565,[]],
			["プライヤー、ペンチ","","pliers",566,[]],
			["レンチ、スパナ","","wrench",567,[]],
			["手びきノコギリ","","handsaws",568,[]],
			["電動のこ","","power saw",569,[]],
			["携帯用電動丸のこ","","circular saw",570,[]],
			["チェーンソー","","chain saw",571,[]],
			["手動ドリル","","manual drill",572,[]],
			["電動ドリル","","power drills",573,[]],
			["平削り・形削り工具","","planing and shaping tools",574,[]],
			["サンダー","","sander",575,[]],
			["衛生工具","","plumbing tools",576,[]],
			["電設工具","","electrician's tools",577,[]],
			["計測器具","","measuring tools",578,[]],
			["塗装用具","","painting tools",580,[]],
			["スイスアーミーナイフ","","Swiss army knife",581,[]]]],
		["園芸用具","","",,[
			["園芸用具","","gardening implements",582,[]],
			["スプリンクラーとノズル","","sprinkler and nozzles",583,[]],
			["芝刈り機","","lawn mower",584,[]],
			["手押し車および種まき機","","wheelbarrow and seeder",585,[]]]],
		["牧童用具","","ranching gear",586,[]],
		["わな","","traps",587,[]],
		["農耕器具","","",,[
			["トラクター","","tractors",588,[]]]],
		["建設機械","","",,[
			["ブルドーザー","","bulldozer",590,[]],
			["削岩機","","rock drill",592,[]],
			["転鏡儀","","transit",593,[]]]],
		["科学用器具","","",,[
			["顕微鏡","","microscope",594,[]],
			["望遠鏡と双眼鏡","","telescope & binoculars",595,[]]]],
		["センサー","","",,[
			["暗視装置と測遠装置","","night vision system and rangefinder",596,[]],
			["探知機","","detectors",597,[]],
			["レーダー","","radar",598,[]],
			["水中音波探知装置","","sonar",599,[]],
			["実験用具","","laboratory equipment",600,[]]]],
		["計算用具","","",,[
			["投票用紙記入所","","voting booth",602,[]]]],
		["安全装置","","",,[
			["丁番と掛け金","","hinge and hasp",604,[]],
			["鍵及び南京錠","","key and padlock",605,[]],
			["ドアロック","","door locks",606,[]],
			["金庫室および金庫","","vault and safe",607,[]]]],
		["鎖と滑車","","chain and pulley",608,[]]]],
	["生物","","LIVING THINGS",609,[
		["人間","","",,[
			["人体","","the human body",610,[]],
			["身体各部の文学的呼称","","literary anatomy",611,[]],
			["人体部分名称（日英語の比較）","","names of the body parts",612,[]],
			["骨格系及び筋系","","skeleton and muscular system",614,[]],
			["内臓","","internal organs",615,[]],
			["生殖器官","","sexual organs",616,[]],
			["感覚器官","","sense organs",617,[]],
			["四肢","","the extremities",619,[]]]],
		["食用動物","","",,[
			["牛","","cow",622,[]],
			["羊","","sheep",623,[]],
			["豚","","pig",624,[]],
			["家禽","","poultry",625,[]]]],
		["家畜","","",,[
			["犬","","dog",626,[]],
			["猫","","cat",627,[]],
			["馬","","horse",628,[]]]],
		["野生動物","","",,[
			["鳥","","bird",630,[]],
			["クモ","","spider",631,[]],
			["昆虫","","insects",632,[]],
			["は虫類","","reptiles",634,[]],
			["両生類","","amphibians",636,[]],
			["海洋生物","","marine life",638,[]],
			["有殻動物","","shellfish",640,[]],
			["複合獣","","ultimate beast",642,[]],
			["恐竜","","dinosaurs",644,[]],
			["怪獣","","monstrous beasts/monsters",645,[]]]],
		["植物","","",,[
			["樹木","","tree",646,[]],
			["根系","","root system",647,[]],
			["葉","","leaf",648,[]],
			["花","","flower",649,[]],
			["野菜","","vegetables",650,[]],
			["くだもの","","fruits",651,[]],
			["草","","grass",652,[]],
			["特殊植物","","special plants",653,[]]]],
		["多肉植物","","succulents",654,[]]]],
	["地球","","THE EARTH",655,[
		["太陽系","","",,[
			["宇宙","","the universe",656,[]]]],
		["地球","","",,[
			["地球","","Earth",658,[]],
			["風と海流","","wind and ocean currents",660,[]],
			["標準時差表","","standard time",662,[]]]],
		["地形","","",,[
			["地形","","land features",664,[]],
			["海岸線と大陸縁辺部","","coastline and continental margin",665,[]],
			["山","","mountains",666,[]],
			["火山","","volcano",668,[]],
			["地震","","earthquake",669,[]],
			["洞窟断面","","cave cross section",670,[]],
			["氷河","","glacier",671,[]]]],
		["水系","","",,[
			["河川","","river",672,[]],
			["波と水際","","wave and shoreline",673,[]]]],
		["気象","","",,[
			["雲","","clouds",674,[]],
			["暴風系","","storm systems",676,[]],
			["天気図","","weather map",678,[]],
			["気象観測器","","weather monitoring equipment",680,[]]]],
		["地図","","",,[
			["市街図","","city map",682,[]],
			["道路地図","","road map",683,[]],
			["地図","","map",684,[]],
			["地形図","","topographic map",686,[]],
			["主題図／分布図","","thematic/distribution maps",687,[]],
			["海図","","nautical chart",688,[]]]]]]];
